#!/bin/bash
export MESOS_NATIVE_LIBRARY=/usr/local/lib/libmesos.so
export SPARK_JAVA_OPTS="-XX:+UseConcMarkSweepGC -Dspark.cleaner.delay=100"
export SPARK_MEM=1024m
java -Dspark.cleaner.delay=100 -XX:MaxPermSize=256M -Xmx1g -jar $(dirname $0)/sbt-launch.jar "$@"
